### ISSUE TITLE
More relaxed default for `headerParserRegex`?

### ISSUE THREAD

**Issue by JojOatXGME** [JetBrains/gradle-changelog-plugin#16]
Hi, I was wondering if there is a specific reason for `headerParserRegex` being so restrictive by default. In my case I noticed that the default does not allow versions with more than 3 parts (e.g. `0.1.0.0`).

The current default for the regex is the following.

```regex
^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?${'$'}
```

I wouldn't expect this plugin to verify the format of my versions. Why not let the user choose whatever format they like. I would therefore suggest changing the regex to one of these.

```regex
^[0-9a-zA-Z]([-._+]?[0-9a-zA-Z])*$
^[-._+0-9a-zA-Z]+$
```

**Comment by hsz** [comment]
@JojOatXGME  Thanks for asking. The current default regex is a rule that comes from the SemVer documentation.
I'll keep it for sure, because thanks to it, you can also be sure that the specified version is valid.

Users still can specify their own, more relaxed rules with the `headerParserRegex` property you've mentioned.

**Comment by JojOatXGME** [comment]
@hsz Thanks for the quick reply. I agree that it is easy to set `headerParserRegex` and it is therefore not a big problem. I will still try to explain my objections a last time. Validating the version string might be a useful functionality and embracing semantic versioning is reasonable. Anyway, the [section about *convention over configuration*] in the Gradle documentation states

> When writing your own plugins, make sure that you pick sensible defaults. You can find out if you did pick sensible conventions for your plugin if you see that the majority of plugin consumers don’t have to reconfigure them.

Having to change the configuration for a feature I don't care about feels a bit odd to me. The main value of the validation seems to be protecting previous releases in the changelog from manual tampering. Note that the `patchChangelog` task does not verify the format and might actually generate an invalid file. I'm not sure if developers making previous versions in the changelog invalid is actually a common concern.

[section about *convention over configuration*]:
<https://docs.gradle.org/nightly/userguide/designing_gradle_plugins.html#convention_over_configuration>
"Designing Gradle plugins"

**Comment by ChrisCarini** [comment]
To add another perspective (and, let me preface this with the fact it's not *directly* related to the original issue, but close enough, in my perspective) - the `README.md`'s example usage actually has a `headerParserRegex` set to something that does **not** (from my understanding / parsing of the semver docs) follow semver. I would have preferred this was omitted in the example - I copied and pasted it, and in a rush did not even notice that the default was something reasonable.

I do see a decent argument that this plugin is for the [keep a changelog](https://keepachangelog.com/), which does not **enforce** that projects using it make use of semver, but it does state that projects should:

> **_Mention_** whether you follow Semantic Versioning.

(emphasis on `mention` my own).

It seems reasonable to me that this plugin pick a sensible default (use semver), and provide the ability for users to override - my gut tells me that more than 50% of projects using this plugin might follow semver, I'd rather that be data-backed (instead of gut-backed), perhaps there is some way to extract that from GitHub? I am not sure.

**Comment by hsz** [comment]
@ChrisCarini Good point, thanks.
